# Generated by Django 3.1.4 on 2020-12-16 19:07

import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Use to display the page of the workshop with all the data about the results and praticipants', primary_key=True, serialize=False)),
                ('workshop_code', models.CharField(default=api.models.random_string, editable=False, help_text='A 6 digit unique code, use to refer the workshop when sending the results', max_length=10, unique=True)),
                ('admin_code', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Code used to delete workshop/results', unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True, help_text='timestamp of the creation')),
                ('workshop_name', models.CharField(help_text='Name of the workshop', max_length=100)),
                ('admin_name', models.CharField(help_text='Name of the admin', max_length=100)),
                ('participants_nb', models.IntegerField(help_text='Number of the participants (only visual help)')),
                ('admin_email', models.EmailField(help_text='Email of the admin used to send him an email with all the informations', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(blank=True, help_text='Email of the user submitting the result (use to send him a confirmation and keep him up to date with the workshop results later)', max_length=254)),
                ('data', models.JSONField(help_text='The actual result data in json format')),
                ('group_name', models.CharField(max_length=100)),
                ('workshop_code', models.ForeignKey(help_text='The workshop_code value, use to refer the result to the workshop', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.workshop', to_field='workshop_code')),
            ],
        ),
    ]
