# Generated by Django 3.1.4 on 2020-12-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='email_access_sent_nb',
            field=models.IntegerField(default=0, help_text='Number of email result access sent to the users (use to limit the nb of email to avoid spam)'),
        ),
    ]
