version: "3.4"

services:
    django:
        build: 
          context: .
          target: django-dev
        env_file: ./configurations/api/api.env      
        volumes:
            - .:/src
            - ./secrets/api:/run/secrets/:ro
            - staticfiles:/src/aggregator/staticfiles
        ports:
          - 8000:8000

    postgres:
      image: postgres:11
      env_file: ./configurations/postgres/postgres.env
      ports:
        - "5432:5432"
      volumes:
      - ./secrets/postgres:/run/secrets/:ro
      - postgresdata:/var/lib/postgresql/data

volumes:
    postgresdata:
    staticfiles: