name: remote ssh command
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        # host: ${{ secrets.HOST }}
        # username: ${{ secrets.USERNAME }}
        # password: ${{ secrets.KEY }}
        # port: ${{ secrets.PORT }}
        script: ls -la
